name: ga
channels:
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0=py36_0
  - backcall=0.1.0=py_0
  - backports=1.0=py36_1
  - backports.functools_lru_cache=1.5=py36_0
  - bleach=2.1.3=py_0
  - ca-certificates=2018.4.16=0
  - certifi=2018.4.16=py36_0
  - cffi=1.11.5=py36_0
  - chardet=3.0.4=py36_0
  - cryptography=2.2.1=py36_0
  - cycler=0.10.0=py36_0
  - dbus=1.11.0=0
  - decorator=4.3.0=py_0
  - entrypoints=0.2.3=py36_1
  - expat=2.2.5=0
  - fontconfig=2.12.1=4
  - freetype=2.7=1
  - gettext=0.19.8.1=0
  - glib=2.55.0=0
  - gmp=6.1.2=0
  - gst-plugins-base=1.8.0=0
  - gstreamer=1.8.0=1
  - html5lib=1.0.1=py_0
  - icu=58.2=0
  - idna=2.6=py36_1
  - ipykernel=4.8.2=py36_0
  - ipython=6.4.0=py36_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.2.1=py36_1
  - jedi=0.12.0=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=2
  - jsonschema=2.6.0=py36_1
  - jupyter=1.0.0=py_1
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36_0
  - jupyter_contrib_core=0.3.3=py36_1
  - jupyter_contrib_nbextensions=0.5.0=py36_0
  - jupyter_core=4.4.0=py_0
  - jupyter_highlight_selected_word=0.2.0=py36_0
  - jupyter_latex_envs=1.4.4=py36_0
  - jupyter_nbextensions_configurator=0.4.0=py36_0
  - jupyterthemes=0.19.1=py_0
  - lesscpy=0.13.0=py36_0
  - libiconv=1.15=0
  - libpng=1.6.34=0
  - libsodium=1.0.16=0
  - libxcb=1.13=0
  - libxml2=2.9.8=0
  - libxslt=1.1.32=0
  - lxml=4.2.1=py36_0
  - markupsafe=1.0=py36_0
  - matplotlib=2.1.0=py36_0
  - mistune=0.8.3=py36_1
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py36_0
  - notebook=5.5.0=py36_0
  - openssl=1.0.2o=0
  - pandas=0.23.0=py36_1
  - pandoc=2.2.1=0
  - pandocfilters=1.4.2=py36_0
  - parso=0.2.1=py_0
  - pcre=8.41=1
  - pexpect=4.5.0=py36_0
  - pickleshare=0.7.4=py36_0
  - ply=3.11=py36_0
  - prompt_toolkit=1.0.15=py36_0
  - ptyprocess=0.5.2=py36_0
  - pycparser=2.18=py36_0
  - pygments=2.2.0=py36_0
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.2.0=py36_0
  - pyqt=5.6.0=py36_5
  - pysocks=1.6.8=py36_1
  - python-dateutil=2.7.3=py_0
  - pytz=2018.4=py_0
  - pyyaml=3.12=py36_1
  - pyzmq=17.0.0=py36_4
  - qt=5.6.2=3
  - qtconsole=4.3.1=py36_0
  - requests=2.18.4=py36_1
  - send2trash=1.5.0=py_0
  - simplegeneric=0.8.1=py36_0
  - sip=4.18=py36_1
  - six=1.11.0=py36_1
  - sqlite=3.13.0=1
  - terminado=0.8.1=py36_0
  - testpath=0.3.1=py36_0
  - tornado=5.0.2=py36_0
  - traitlets=4.3.2=py36_0
  - urllib3=1.22=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - xorg-libxau=1.0.8=3
  - xorg-libxdmcp=1.1.2=3
  - yaml=0.1.7=0
  - zeromq=4.2.5=1
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libopenblas=0.2.20=h9ac9557_4
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - ncurses=6.1=hf484d3e_0
  - numpy=1.14.3=py36h28100ab_1
  - numpy-base=1.14.3=py36h0ea5e3f_1
  - pip=10.0.1=py36_0
  - python=3.6.2=0
  - readline=6.2=2
  - setuptools=39.1.0=py36_0
  - tk=8.5.18=0
  - wheel=0.31.1=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=ha838bed_2
prefix: /home/greg/miniconda3/envs/ga

